using Microsoft.AspNetCore.SignalR;

namespace AiChat.Api.Hubs;

/// <summary>
/// Manages SignalR subscriptions for client-generated streaming request identifiers.
/// </summary>
public sealed class ChatHub : Hub
{
    /// <summary>
    /// Adds the current connection to the group that receives events for a request.
    /// </summary>
    /// <param name="requestId">The request identifier generated by the React client.</param>
    /// <returns>A task that completes when the connection has joined the group.</returns>
    public Task JoinRequest(Guid requestId)
    {
        return Groups.AddToGroupAsync(
            Context.ConnectionId,
            GetRequestGroupName(requestId));
    }

    /// <summary>
    /// Creates the shared SignalR group name for a request identifier.
    /// </summary>
    /// <param name="requestId">The request identifier represented by the group.</param>
    /// <returns>The canonical request group name.</returns>
    public static string GetRequestGroupName(Guid requestId)
    {
        return $"request-{requestId}";
    }
}
